### ISSUE TITLE
Also save binary executables for linux and mac?

### ISSUE THREAD

**Issue by LiHRaM** [LiHRaM/vscode-tcc-compiler#11]
The Tiny C Compiler can run on both of those too, but they'd need to be compiled. Maybe as the extension is installed?

**Comment by haudan** [comment]
Why are you including the entire TCC? Why not let the user specify the path to their TCC installation?

**Comment by LiHRaM** [comment]
@Lisoph For the sake of convenience. _Not_ having to set anything up is one of the attractions, I believe. (Plus, even if users of this extension had TCC installed twice, it would make practically no difference, due to the tiny size of the compiler.)
Although considering that Mac and Linux have the GCC toolchain built in, I don't really think this issue is necessary
